[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ioredis", "minecraft-server-util"]

[[plugins]]
  package = "@netlify/plugin-nextjs"


# Environment variables for Netlify
# Add these in Netlify Dashboard > Site Settings > Environment Variables
# NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
# NEXT_PUBLIC_SUPABASE_ANON_KEY=your_anon_key
# SUPABASE_SERVICE_KEY=your_service_key


