[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.4"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ioredis", "minecraft-server-util"]

[[plugins]]
  package = "@netlify/plugin-nextjs"


